// Leetcode 389. Find the Different
/*Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e
*/
//Explanation:
//'e' is the letter that was added.

package main

import (
	"fmt"
)

func main() {
	s := "abcd"
	t := "abcde"
	fmt.Println(findTheDifferent(s, t))
}

func findTheDifferent(s, t string) string {
	var dif int
	for _, val := range s {
		dif = int(val-'a') ^ dif
	}
	for _, val := range t {
		dif = int(val-'a') ^ dif
	}
	return string('a' + dif)
}
